import {Metadata} from 'next';
import {Fira_Sans_Condensed} from 'next/font/google';
import './globals.css';

const fira = Fira_Sans_Condensed({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Pomofocus',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang='en'>
      <body className={fira.className}>{children}</body>
    </html>
  );
}
